sudo: required

language: generic

services:
  - docker

env:
  global:
    - HOME_BUILD=$HOME/build
    - ROS2WS=$HOME_BUILD/ros2_java_ws

cache:
  directories:
    - $ANDROID_HOME

before_install:
- docker pull theosakamg7/ros2java:latest
- echo "INSTALL/BUILD ROS2 AMENT..."
- cd $HOME_BUILD && mkdir -p ament_ws/src && cd $HOME_BUILD/ament_ws
- docker run -u "$UID" -it --rm -v `pwd`:`pwd` -w `pwd` theosakamg7/ros2java:latest sh -c "/usr/bin/wget https://gist.githubusercontent.com/Theosakamg/e6084cfafa6b7ea690104424cef970a2/raw/ament_java.repos"
- docker run -u "$UID" -it --rm -v `pwd`:`pwd` -w `pwd` theosakamg7/ros2java:latest sh -c "/usr/bin/vcs import src < ament_java.repos"
- docker run -u "$UID" -it --rm -v `pwd`:`pwd` -w `pwd` theosakamg7/ros2java:latest sh -c "src/ament/ament_tools/scripts/ament.py build --symlink-install --isolated"
- echo "INSTALL ROS2 WS..."
- cd $HOME_BUILD && mkdir -p $ROS2WS/src && cd $ROS2WS
- docker run -u "$UID" -it --rm -v `pwd`:`pwd` -w `pwd` theosakamg7/ros2java:latest sh -c "/usr/bin/wget https://gist.githubusercontent.com/Theosakamg/d9259bbc708c5145255fbdeb25e65e19/raw/ros2_java_desktop.repos"
- docker run -u "$UID" -it --rm -v `pwd`:`pwd` -w `pwd` theosakamg7/ros2java:latest sh -c "/usr/bin/vcs import src < ros2_java_desktop.repos"
- cd $ROS2WS/src/ros2/rosidl_typesupport && patch -p1 < ../../ros2_java/ros2_java/rosidl_ros2_java.diff
- echo "INSTALL ALFRED WS..."
- cd $ROS2WS
- docker run -u "$UID" -it --rm -v `pwd`:`pwd` -w `pwd` theosakamg7/ros2java:latest sh -c "/usr/bin/wget https://gist.githubusercontent.com/Theosakamg/51f3e8670784db13d9190c58e3e57eb2/raw/ros2_alfred.repos"
- docker run -u "$UID" -it --rm -v `pwd`:`pwd` -w `pwd` theosakamg7/ros2java:latest sh -c "/usr/bin/vcs import src < ros2_alfred.repos"
- rm -rf $ROS2WS/src/rosalfred/smarthome_common_driver && ln -s $HOME_BUILD/rosalfred/smarthome_common_driver $ROS2WS/src/rosalfred/smarthome_common_driver
- echo "BUILD ROS2 WS..."
- cd $HOME_BUILD && ls -lFa ./ && find . -maxdepth 3 -type d -not \( -path "./.git" -prune \)
- docker run -u "$UID" -it --rm -v `pwd`:`pwd` -w `pwd` theosakamg7/ros2java:latest sh -c ". ament_ws/install_isolated/local_setup.sh && cd $ROS2WS && ament build --symlink-install --isolated"

script:
- cd $HOME_BUILD && docker run -u "$UID" -it --rm -v `pwd`:`pwd` -w `pwd` theosakamg7/ros2java:latest sh -c ". ament_ws/install_isolated/local_setup.sh && cd $ROS2WS && ament test --isolated --only smarthome_common_driver"

after_success:
  - coveralls

